logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
  config: classpath:logback-dev.xml

spring:
  application:
    name: kb-tool-service
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    open-in-view: true
    show-sql: true
  datasource:
    max-active: 15
    max-idle: 10
    max-wait: 8000

application:
  datasource:
    uri: mongodb+srv://%s:%s@cluster0.xtlunus.mongodb.net/test
    database: kb-tool-service
    user: mongodb-vutran
    pwd: USTzBPPDPRo2EGbv

server:
  port: 8080